# -*- coding: utf-8 -*-
"""24-09-02-hello-world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v1UoUAIdF6vnwcUWIaNMt_kwqEv-4rmA
"""

print("Hello World")

